### PR TITLE
Consolidation of forks

### PR DESCRIPTION
**Pull request by arseny92**
Consolidation

Disclaimer: for issues with changes I do not own, please contact the forks in question: use the network view

Questions regarding calypso/c376 go here

### CODE REVIEW

**Comment by ybaruchel** [comment]
Hi @arseny92 , 
How can I try your changes on my cardpeek installation? Can you please provide more info on how to test the changes you've made?

**Comment by arseny92** [comment]
@ybaruchel 

Sure. First, install the normal version of Cardpeek. 
Then apply my changes of **dot_cardpeek_dir** to your Cardpeek user folder at **C:\Users\<user>\.cardpeek** to use the updated scripts 

* -updated a typo, added issuer 98. 
* -review of [recent additions to MOT rules](https://www.gov.il/he/departments/general/smart_ticketing) is still underway when I'll have some time for this (updates of contract lists, etc.) ;)

Note that there are still a few issues with this, as somehow (unsure how) I broke e.g. the showing of the profile/card issuance/expiration dates, and since my Lua skills are mostly voodoo programming, not sure how to fix that and some other things. If anyone proficient with Lua can check, you may submit a pull request to my fork.

**Comment by tomer8007** [comment]
> I broke e.g. the showing of the profile/card issuance/expiration dates

@arseny92 I had the `en1545_DATE` fields not showing too, and in my case I could make it work by removing the `%a ` from [this line at en1545.lua](https://github.com/L1L1/cardpeek/blob/master/dot_cardpeek_dir/scripts/lib/en1545.lua#L28). Does that work for you maybe?

**Comment by arseny92** [comment]
@tomer8007 I figured out why `en1545_DATE` not working. It only works correctly if the system date format is mm/dd/yyyy (US). The output format is weekday mm/dd/yyyy. It's just that en1545.lua needs to be updated to support other date formats. Nothing to do with the string variable you removed.

**Comment by tomer8007** [comment]
>  review of [recent additions to MOT rules](https://www.gov.il/he/departments/general/smart_ticketing) is still underway when I'll have some time for this (updates of contract lists, etc.) ;)
> 
@arseny92 Have any idea of where the "030721SDI-NT-DataModel" document is?

**Comment by arseny92** [comment]
@tomer8007 That specific document as far as I'm aware is only published by MOT to transit operators and companies that actually need the specification to operate ([Pcentra](https://ravkavonline.co.il/he/), [HopOn](https://hopon.co.il/) etc.).
Which means, 99% of the entire c376 script (and ravkav-strings.lua) come from the other files' data, contained in that zip, about how all this is supposed to work, combined with data from transit operators tender agreements (such as [this](https://www.gov.il/BlobFolder/guide/agreements_for_operating_service_lines_in_public_transportation/he/matronic_tender_attache_d.pdf)) combined with [public information about the **upstream** CNA standard](https://www.calypsonet-asso.org/documents?title=&field_date_value[value][month]=&field_date_value[value][year]=&field_categorie_tid[0]=23&step=1&page=13) without the local Israeli differences - such as [this](https://www.calypsonet-asso.org/sites/default/files/010608-NT-CalypsoGenSpecs15.pdf). Sometimes even just original research in the form of try/error guesswork produced the right fields parsing...

**Comment by ybaruchel** [comment]
@arseny92 
You're welcome :)
https://github.com/ybaruchel/ravkavlibrary

**Comment by tomer8007** [comment]
@ybaruchel Nice, where did you get this from? last time I decompiled `com.pcentra.ravkavonlinemobile.apk` it didn't turn out so clear

**Comment by ybaruchel** [comment]
It’s not the ravkavonline app, but I also managed to decompile the ravkavonline app and the HopOn app. There is some helpful info there.

**Pull request merged**
